name: prog_languages_flutter
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: MateSC-Regular
      fonts:
        - asset: assets/fonts/MateSC-Regular.ttf
    - family: OpenSansCondensed-Light
      fonts:
        - asset: assets/fonts/OpenSansCondensed-Light.ttf
    - family: Lateef-Regular
      fonts:
        - asset: assets/fonts/Lateef-Regular.ttf
    - family: Quicksand-VariableFont_wght
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght.ttf
        